### ISSUE TITLE
Persia Improvement

### ISSUE THREAD

**Issue by Arcvalons** [loup99/WtWSMS#118]
Some months ago in the forum there was a thread discussing the Sassanids, the "Persian Expansion & Reconquest Discussion" thread. So I was wondering if there was any consensus reached in that regard? 

To expand on it, I also wanted to know if Persia is supposed to get its own government-type based on the Bureucratic one, and if a reworking of the provinces in Persia is planned at all. 

I would be willing to work on all this, of course.

**Comment by EWattman** [comment]
I'll basically quote myself: <<"Non-rapid Expansion? Then what do you call the result of the Byzantine-Sassanian War in 602-628? The Persians conquered Egypt, the Oriens and half of Anatolia, all in one single war. They only lost it because of the convenient civil-wars that allowed the Muslims to ass-stomp them. And they scored a lot of conquests in the 3rd Century too. But most of the time, the reason that they couldn't conquer anything, was that the Romans simply had them outmatched.

Theese are the conquests of the Sassanids, in a single war, when they were at their peak:
https://upload.wikimedia.org/wikipedia/commons/a/a6/Sassanian_Empire_621_A.D.jpg

Imperial Reconquest sounds good, but it would have to be a Kingdom-wide CB that is valid for all the territories of the ancient Achamenids, under Darius I:
https://upload.wikimedia.org/wikipedia/commons/e/e7/Achaemenid_empire_map_expansion.png

This means that the Sassanids would be able to take all of the territory of the ERE in those wars, except for Achaia, Macedonia and Moesia Superior. In short, the Imperial Reconquest would be valid for all kingdoms from Moesia Inferior to Syria to Egypt. Also, the Caucasian Kingdoms and Taurica would be included by this CB.

However, Yemen would not be included. It only fell under direct Persian control in the late 6th Century.">>

However, a government unique to Persia has been dicsussed on occation, but wasn't really accepted as a thing we would do.

And Enlil and I had planned to get to redesign the Persian provinces after the 1.0.0 is released.

**Comment by Arcvalons** [comment]
> And Enlil and I had planned to get to redesign the Persian provinces after the 1.0.0 is released.

Did you have anything specific in mind about that?

**Comment by Arcvalons** [comment]
This is what I was doing with the province layout in Persia before I read your message, I just started by reshaping some provinces but then I realized I would need to add a few more provinces.

![Southern Persia](http://i.imgur.com/Vibs9Oh.jpg)
![Khorasan](http://i.imgur.com/0X4OMId.png)
![Baluchistan Provinces Reshaped](http://imgur.com/ICJInL1.png)

And these were the maps I was using for reference:

http://imgur.com/a/6P2Ti

Should I continue, or would you rather do it later on?

**Comment by loup99** [comment]
Out of curiosity: how many new provinces are you thinking would be necessary?

The Sassanids should IMO get their own form, but it will have to be discussed on the forums. Same with the reconquest.

**Comment by Arcvalons** [comment]
I would be adding approximately 50% more provinces, which would be around 30. Most of those would actually be in western Persia and Mesopotamia, which concentrated most of the Sassanid Empite's population back then.

**Comment by EWattman** [comment]
> Did you have anything specific ideas in mind about that?

> This is what I was doing with the province layout in Persia before I read your message, I just started by reshaping some provinces but then I realized I would need to add a few more provinces.

The physical provinces themselves I have no real constructive opinion about. I am more the advisor for the map changes Enlil does, like the positioning of some cities and stuff. Personally, I like to have as many soft-like small and medium-sized provinces, just to get smooth borders everwhere But more I am in charge of the dejure map, which Enlil and I decided to go for the Achaemenid provinces, since those were the only ones I could find clearly established borders for, in this:

http://sitemaker.umich.edu/mladjov/files/achaemenid_satrapies.jpg

The majority of these are good regional names that are still valid.

**Comment by Arcvalons** [comment]
Oh, I agree with the small and medium province structure to make the borders look nice. That's what you guys did in Syria/Oriens, right?  I don't see any problem with using the Achaemenid de-jure structure either, though for dejure kingdoms I suggest using the Sassanid-era 'kusts' established by Khosrau I. I'll continue re-drawing the province map and show you guys here any progress.

Here's about the Kust system used by the Sassanians:

>The sassanid empire ('Irānshahr') was divided into four parts each called a 'Kūst'.

>The four Kusts operated independently in their economic affairs through 'divān', a bureau with job titles such as 'dabir' (Scribe, or a general employee), and 'āmārgar' (accountant). The Military affairs of each Kust was made independent after the reign of Anushirvān: This was done mostly to control constant invasions from all borders of Iran:

>1) The northwestern Kust was called "Aturpātagān" (Fire-keeper) and was one of the most active fronts, in both religious practice and military maneuvers. This was where most of the resources to hold back Roman and Byzantine invasions were centered and where assaults were planned. Media (Kurdistan and Central Iran), Assyria, Azerbaijan, Armenia, Georgia, Hyrcania, and the Caspian shores were the major lands in this Kust.

>2) The northeastern Kust was called "Xurāsān" (Sunrise), a vast land which reached the Himalayas in the east, included the central Iranian deserts in the west and at times occupied parts of Kazakhstan in the north. In its northern fronts, Sakas, Huns, Hephtalites, Turks and several other nomadic people launched constant raids and were repelled by local Marzpāns. Due to its far reaches and lose control of the central government, this land housed many minorities which were otherwise prosecuted by the Zoroastrian priests. Economic prosperity of this land was guaranteed through trade routes which connected Rome, Persia and China.

>3) The southeastern Kūst was called "Nimruz" (Mid-day), a land which consisted of Sistan, Pakistan and southern Afghanistan. Little is known about the history of these parts of the empire, where Sassanids had a friendly relation with the empires of India.

>4) The southwestern part was called "Xurvarān" (west), where the Sassanid royalty originated and the heart of the Empire was located. The lands of Persia, Yazd, Khuzistan, Arabia, Iraq and the shores of Persian Gulf were parts of this Kust. This was a generally prosperous and secure land, despite occasional raids by Arab nomads. 

What do you think?

**Comment by EWattman** [comment]
That would look something like this:

http://imgur.com/DdXVtA3

Im sure that these operated very well in their day, but I am hesitant to use these. Consider:

These are Persian(and especially Sassanid)-specific provinces. What happens if the Hepthalites conquer Persia, if India decides to do something or Rome comes in? Not to spoil anything, but Khosrow doesn't become king until 531, which is after the start date. It is better to have established geographical and cultural regions that everybody can work with as dejure rather than nation-specific provinces.

**Comment by Arcvalons** [comment]
Hmm. You are right, that de-jure setup doesn't look very pleasing aesthethically either. Althought with more provinces, I think a partition of at least de-jure k_persia can probably be justified. Now...

![Sassanian Mesopotamia](http://i.imgbox.com/Wx33YQwL.png)

Here's what I did in Mesopotamia, though I think it could use a couple more provinces in the Lakhamid side of the Euphrates River and along with the border with the ERE.

**Comment by EWattman** [comment]
Yeah, Sinjar could definetly be split up and those large provinces bordering Armenia. K_persia would be represented by the Kingdom of Persis. The Lakhmids themselves should look like something like this:

http://nyx.meccahosting.com/~a00052c7/croppedsevenkingdomsmodifiedbynatalee.jpg

I will talk to Enlil. Since he can't use Github, he can't se these changes. But I'll talk to him and see if your work can be used instead of our planned. Though I would suggest you keep out of Armenia and the Caucasus for now, atleast until I hear from him.

**Comment by Arcvalons** [comment]
Of course, I'll wait to see what you guys decide then. By the way, the link you posted earlier with the Achaemenid Satrapies is broken now (I didn't save it...), apparently that whole site, and all the maps there, have been taken down.

**Comment by EWattman** [comment]
I know, unfortunately. However there are similar maps, with less defined borders, but with all the provinces still in the right place, like this:

http://edugeography.com/images/persian-empire/persian-empire-05.jpg

**Comment by EWattman** [comment]
Enlil just answered me and we have full permission to mess around with Persia. But as I said, he and I are doing the Oriens and Armenia, so you and I are going to have to stay out of those areas.

**Comment by loup99** [comment]
Has this province overhaul advanced since December? Anything you need help with?

**Comment by Arcvalons** [comment]
I finished all of Mesopotamia and began with the western edge of Persia
proper back in January, but I haven't got anything else done after that,
since my build is a WTWSMS version and like three major vanilla patches
behind.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2115-v2-a>
This
email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-2115-v2-a>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-03-30 1:45 GMT-06:00 Loup <notifications@github.com>:

**Comment by loup99** [comment]
Do you want help to update it?

**Comment by Arcvalons** [comment]
Sure, that'd be great. I believe I've added all the changes I've made to my branch on my profile, if you want to take a look.

**Comment by loup99** [comment]
OK, I will look at it.

**Comment by loup99** [comment]
I have created a branch with your changes, and will update it to the latest version.

**Comment by Arcvalons** [comment]
Thanks, that will help a lot.

**Comment by Arcvalons** [comment]
So I went on to expand the map overhaul to central and eastern Persia, but I hit a roadblock in the form of a CTD whileloading the game. The graphics log says "Province 0 has invalid origin" and "Province 1535 has invalid orgin" but I doubt that is it. 

Anyone has any idea what it might be? Right now the provinces have no histories or title attached to them, but the game loaded them as grey provinces fine until suddenly it didn't anymore, hmmm.

**Comment by loup99** [comment]
Have you increased the numbers of provinces in default.map?

**Comment by Arcvalons** [comment]
Oh, it was terrain.bmp, I edited it and didn't realize it was supposed to be indexed.

Anyway, I've almost completed southern and central persia now:
http://imgur.com/6jd6gIs.png
http://i.imgur.com/C7BMfqp.png

And I made Mesopotamia greener (can I do that?) :
http://i.imgur.com/9NTWvyy.png

**Comment by loup99** [comment]
Great work! As for changing the terrain to be more green, if it is historical (I'm not an expert on this domain) of course you can.

**Comment by EWattman** [comment]
Well, North Africa was greener back in the day and with it being the most populated and likely irrigated areas of Persia, I think its safe to say that Mesopotamia was greener.

**Comment by loup99** [comment]
I believe this is now done on both branches bar some minor corrections. Closing the issue.
