### ISSUE TITLE
Why Don't Restored Legions Take Your Culture and Religion?

### ISSUE THREAD

**Issue by TurtleShroom** [loup99/WtWSMS#159]
Good afternoon.

I am writing to point out something that struck me as odd. When a player restores a Roman Legion, they automatically become Roman and Nicene, and cannot be changed. This is especially odd if Hellenism takes over Rome, or if a heresy or foreign faith seizes power.

The Roman Legions in RL were hardly so monolithic. Many ancient centurions were not devoted Hellenics (and indeed, the Bible says one even converted to Judaism and spent money building synagogues before converting after asking Jesus to heal his relative). Not all of them were culturally Roman, either, even though they all were supposed to have absolute loyalty to the Roman Empire.

What I propose is that whenever a character with the appropriate Latin/Byzantine Culture restores a Roman Legion, the Legion's Culture and Religion is set to match the person who took the Decision. That would also allow future rulers to restore it and flip the Legion if it falls out of Roman control.

I'd code it, but I don't know how.

-TURTLESHROOM

**Comment by EWattman** [comment]
I think this could be good and this is the code that creates that commander:

# Random legion commander  when organizing legions
create_legion_commander_effect = {
	create_random_soldier = {
		random_traits = yes
		culture = roman
		dynasty = NONE
		female = no
		age = 34
		attributes = {
			martial = 8
		}
		trait = skilled_tactician
	}
}

So its proabably only a question of altering culture to PREV, LIEGE or FROM or whatever the appropriate thing is. But Im not sure if that works.

**Comment by loup99** [comment]
No random foreign powers should be allowed to restore legions.

**Comment by EWattman** [comment]
That shouldn't be a problem, since that is checked of in the overall creation of the legion, not the commander.

**Comment by TurtleShroom** [comment]
Are there any updates concerning this Issue?

**Comment by loup99** [comment]
Nothing at the momemt.

**Comment by NicolasGrosjean** [comment]
I have tested it by the following instructions:
- In decisions/WtWSMS_organise_legions_decisions.txt, comment the line completely_controls = d_pannonia_superior (line 19)
- Launch the game
- In the first bookmark, take the Eastern Roman Emperor
- Open the console and type the following commands
   - give_title k_pannonia 145226
   - cash
- The decision to create a legion is available: take it

You have something like that:
![a](https://cloud.githubusercontent.com/assets/13560473/19490849/0bbe8274-9571-11e6-9cfc-91916df83e41.png)

The problem is that the legion commandant has a Vanilla portrait instead of a beautiful roman portrait because he is not roman.

**Comment by loup99** [comment]
Isn't that portrait matter due to you not having the Mediterannean DLC though, Mouchi?

**Comment by NicolasGrosjean** [comment]
I have no DLC, so it surely this.
I don't know which are the portraits modified by the portrait DLCs.

**Comment by TurtleShroom** [comment]
What if you programmed it so that the gu
