### ISSUE TITLE
Please reconsider?

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#169]
?

**Comment by loup99** [comment]
Consider what?

**Comment by MaelgwnGwynedd** [comment]
Keeping me on? I'd like to help.

**Comment by loup99** [comment]
Keeping you on what? On the PI forums? I'm not going to discuss the rules of that board nor what you posted there that was not in accordance to it.

**Comment by MaelgwnGwynedd** [comment]
Then I'm no longer on the team?

**Comment by loup99** [comment]
I can't speak for the forum staff, sorry.

**Comment by MaelgwnGwynedd** [comment]
Not on the forum, for the mod.

**Comment by loup99** [comment]
Nothing has been decided on that matter. But as a general advice from a general perspective, disregarding the mod, team or this context, I would recommend that you reconsider your decision.

**Comment by MaelgwnGwynedd** [comment]
What decision?

**Comment by loup99** [comment]
The decision of doing the action you posted about on the forums.

**Comment by MaelgwnGwynedd** [comment]
You can say the word piracy.

The game stands at about 300 euros, I can't even afford the base 40.

**Comment by loup99** [comment]
Not even 10€? https://www.bundlestars.com/en/bundle/crusader-kings-ii-bundle

**Comment by MaelgwnGwynedd** [comment]
With all the DLC?

**Comment by loup99** [comment]
Sorry, that was an old offer. You do have it for 34,99€. though (https://fr.gamesplanet.com/game/crusader-kings-ii-steam-key--1857-1) You don't need the DLCs.

**Comment by MaelgwnGwynedd** [comment]
I don't NEED them, but I want them.

**Comment by loup99** [comment]
Actually, you have the collection for €36,24 https://www.humblebundle.com/store/crusader-kings-ii-collection

**Comment by MaelgwnGwynedd** [comment]
Interesting. I will look into it.

**Comment by MaelgwnGwynedd** [comment]
I don't regret what I did. I just want to help with the mod.

**Comment by loup99** [comment]
I don't have anything to answer. I won't reconsider my opinion on what you should do, and there is nothing that has been decided. And as much as I'm sure everyone appreciates help, the mod is worked upon and released on the Paradox forums. Thus, the same rules apply.

**Comment by MaelgwnGwynedd** [comment]
Then I won't be helping any longer.

**Comment by loup99** [comment]
Thank you for the help you provided so far.

**Comment by TurtleShroom** [comment]
I take that the gentleman or lady in question ( @MaelgwnGwynedd ) pirated their game.
They violated Paradox Forum bylaws if they did that and of course should be punished accordingly, but I find the idea that Maelgwn should be punished _here_ to be patently absurd.

There is absolutely nothing wrong with being on the receiving end of Internet piracy, nothing whatsoever. It's only when you are the ones producing and distributing the content that you can become questionable about. For gosh sakes, my own parents condone piracy.

Now, to be fair, _**my CK2 game is not pirated whatsoever**_, so this isn't an issue for me. However, I'd like to note that @MaelgwnGwynedd did nothing wrong here.

**Comment by MaelgwnGwynedd** [comment]
All my teachers in school were pirates. My parents and sister are pirates. My friends are pirates, and to boot it's decriminalised (not persecuted) here.

**Comment by TurtleShroom** [comment]
In my country, the only Internet pirates that are arrested and punished are the ones that _produce_ pirated content. My parents literally asked my sister and I to pirate a movie before it was released on DVD, so that my father could enjoy it with us. (We ultimately bought the DVD.)

While @MaelgwnGwynedd deserved her punishment over at Paradox Forums (whose bylaws explicitly forbid Internet piracy and all discussion of it), she deserves nothing of the sort here. She's a Collaborator of this Mod and a higher contributor than me. You shouldn't cast her out for a harmless act as this.

---------

@loup99 , I feel that you need her on the team. To betray her and cast her out for something she did _on a different website than "Github"_ is not something I would expect from a gentleman as yourself. She's already received her punishment. Why punish her here?

**Comment by MaelgwnGwynedd** [comment]
Why are you calling me a woman?

**Comment by loup99** [comment]
Nobody has been condemned or punished for anything

**Comment by TurtleShroom** [comment]
Huh.

I thought that @MaelgwnGwynedd was being drummed out of the Mod because he was disciplined over at the Paradox Forums for using a pirated game. I was afraid you were about to do the same to him on Github.

As for my pronounc choice, I associated "Maelgwn" with "Megan" (and thought it as pronounced "MALE-gwen") and guessed that it was feminine. I apologize and will refer to you as a man in the future.

**Comment by loup99** [comment]
Nobody has been drummed anywhere. I was just constating the facts and giving my opinion on the matter. Furthermore, I don't see the issue.

**Comment by MaelgwnGwynedd** [comment]
It's pronounced Mail-gwin, and it's not my real name.

I was drummed. You weren't giving your opinion, you were trying to force me to buy the game.

**Comment by loup99** [comment]
Maelgwyn, the Paradox Forums has a set of rules. I'm not allowed to discuss them, as by becoming a member of the forum I accepted to not do so. What I can say is that I'm sorry if you felt that wasn't nice or in any way against you, as that wasn't my intent by following the rules of the board.

I never tried to force you into doing anything, I gave my opinion, as you know i have done a multitude of times before. I don't see how this would be any different.

**Comment by TurtleShroom** [comment]
Ah, I was pronouncing it correctly. That's unsual. Anyway, @MaelgwnGwynedd , you are assuming that Loup reported you. Don't blame him for something you don't know he did.

@loup99 , forcing Maelgwn out for doing something you personally do not like and for something he was rightly punished for elsewhere!  If you don't see the issue, _then let him stay_! Maelgwn has clearly demonstrated his loyalty and work ethic; how else would he rank higher than me on this Mod (as a Collaborator).

That said, this is likely a misunderstanding. Maelgwyn, I don't think Loup has ordered you to leave.

**Comment by TurtleShroom** [comment]
It seems that Loup is trying to say that you're still on the Mod team and may continue in business as usual. (Sorry for the post above me, I was beaten to the submission of the post by Loup.)

**Comment by loup99** [comment]
No, what I have done is that I have given my opinion and told how I will procede. That opinion or way of proceeding will not change, and the forum rules will remain.

**Comment by MaelgwnGwynedd** [comment]
Mailgwin isn't the same pronunciation.

He obviously reported me. If not him, that leaves three other people. It's ridiculous to follow rules so religiously, it's a forum. You think you're not even allowed to talk about piracy of the game outside of the forum? They're RULES, not laws.

**Comment by MaelgwnGwynedd** [comment]
No one reads forum rules, and no one reads the terms of agreement on games either. It was not very honourable to report me. I know several of my friends smoke weed, I'm not about to land them for two years in prison because I disapprove or because the law says so.

**Comment by loup99** [comment]
MaelgwnGwynedd If you consider following the rules of the forum or Github as dishonourable, I don't know what I can answer.

**Comment by MaelgwnGwynedd** [comment]
So you rat people out since the forum rules say so? Wow.

**Comment by MaelgwnGwynedd** [comment]
This is OUTRAGEOUS behaviour: "Maelgwyn, the Paradox Forums has a set of rules. I'm not allowed to discuss them, as by becoming a member of the forum I accepted to not do so."

It's completely insane. You're the only person I've ever met who even thinks like that.

**Comment by loup99** [comment]
My only answer to that is: OK, fine, we disagree on that. You think it is insane, I think it is fair.

**Comment by MaelgwnGwynedd** [comment]
It's foolish behaviour. It's the internet, those are some arbitrary rules.

**Comment by loup99** [comment]
Maybe. And everything is relative.

**Comment by MaelgwnGwynedd** [comment]
That's a cop-out.

**Comment by TurtleShroom** [comment]
Morality is never relative.

Dude, if the bylaws say "don't pirate", you don't discuss or brag about your piracy on the forum with that bylaws. Loup did nothing wrong on the Paradox Forums, and you did nothing wrong on Git Hub, but you DID discuss being a pirate over at that forum in violation of their bylaws. You broke a rule, you paid the price.

_**Git Hub**_ does not forbid owners of pirated copies from working on Mods of that pirated game. Loup has no business expelling you on GIt Hub because he dislikes your piracy, but he ABSOLUTELY did the right thing in ratting you out on Paradox.

**Comment by loup99** [comment]
I haven't expelled anyone from GitHub. What I have done is to give my opinion on GitHub.

**Comment by MaelgwnGwynedd** [comment]
I didn't brag about my piracy. I didn't discuss it, I just said "I own a pirated copy of the game", since I was never going to sync anyway.

**Comment by TurtleShroom** [comment]
I know. You said that you had a right to expel him if you wanted to. I didn't say you did.

@MaelgwnGwynedd , Loup is entitled to his opinion. You're still on the team and can contribute at your leisure. Let us drop this issue accordiongly.

**Comment by MaelgwnGwynedd** [comment]
No, fuck this for a laugh.

**Comment by TurtleShroom** [comment]
Very mature. You're really making it hard for me to defend you.

You said "I own a pirated game" on a forum that bans pirated game ownership, so- SURPRISE -you got your rear banned!

**Comment by MaelgwnGwynedd** [comment]
It's idiotic to never use the words piracy or pirate since a forum says you can't ON that forum.

**Comment by MaelgwnGwynedd** [comment]
If you think swearing is immature, this discussion is completely pointless. Breaking the rules and rebelling are the first signs of maturity, not using basic english words like fuck or arse and conforming to rules is immature.

**Comment by loup99** [comment]
If MaelgwnGwynedd doesn't want to contribute, I believe the discussion has reached it's end. Concerning status, that was me trying to help Maelgwn. I don't regret it, but as he left the team, it will change.

**Comment by MaelgwnGwynedd** [comment]
And they're not bylaws, they're rules. And it was cowardly to not even confront me about it, just report my comment after the work I put in.

**Comment by EmperorEnlil** [comment]
I'm putting a stop to this. Full enforcement of the rules is fully within loup99's rights. If that is what happened, loup99 had every right to do what he did if he reported. Loup99 has been one of the most loyal and hardworking members of this mod, he and Erik W have stuck through thick and thin, even when I myself was indisposed of. You have every right to remain on github, and pirate the game, and continue working on the mod, and if so, I would enjoy discussing some possible genealogies with you. You have every right to disagree with loup99, but there is no point in discussing it. This issue is done.

**Comment by loup99** [comment]
On that note this issue is closed. Statuses have been updated, stances explained. Nothing more to discuss.
