### ISSUE TITLE
Ok

### ISSUE THREAD

**Issue by MaelgwnGwynedd** [loup99/WtWSMS#216]
If you're going to say something, don't close it immediately after like a coward.

**Comment by loup99** [comment]
To be honest, you know what I have said about all different relevant topics. In case you have forgotten, you can look it up. If you have any other questions, feel free to ask. Issues are closed when they have served their purpose, and last time serves as an instance when it comes to closing.

**Comment by MaelgwnGwynedd** [comment]
Lol.

**Comment by loup99** [comment]
Anything specific you had in mind? 

Otherwise I will close this too, the mod repository is for coding, not debating. If you don't want to be a part of the mod development and don't care about it, there is no need for laughing here.

**Comment by MaelgwnGwynedd** [comment]
Oh I care, which is why I'm making my own branch my own mod.

**Comment by TurtleShroom** [comment]
Mael, if you would stop being such an A-hole and use your brain, you would realize that Loup and friends are NOT shutting down your Branch or changes. 

They are unnecessarily adding new provinces in the British Isles (no idea why), but even so, they will be incorporating your de jure changes and history once they are through!

Just because you are on hold doesn't mean you are rejected or forgotten! Be patient, your UK changes are valuable and will be added in due time!

**Comment by MaelgwnGwynedd** [comment]
The province changes aren't necessary and will permanently destroy any hope
of the game accurately going to 600 AD let alone 1400 AD.

**Comment by loup99** [comment]
It is clear that the mod is not going to be used by anyone without permission on any repository. MaelgwnGwynedd has explained the purpose of this issue, so it has served it.

**Comment by MaelgwnGwynedd** [comment]
No.

**Comment by loup99** [comment]
Was there any other purpose?
