### ISSUE TITLE
I'm still willing to help BUT

### ISSUE THREAD

**Issue by AzimuthBlast** [loup99/WtWSMS#227]
I will not stop making the case that *the map of Britain does not need to be overhauled*.

I have also researched the Huns and Goths a lot and can help with that element.

**Comment by TurtleShroom** [comment]
We could really use you, and you are absolutely correct about the British provinces.

I assume that you are the same man as @MaelgwnGwynedd  , yes?

**Comment by AzimuthEmp** [comment]
Not banning me would be a start. Plenty in the mod is wrong and you know it.

**Comment by TurtleShroom** [comment]
@AzimuthBlast 

Well, the first thing you need to do is apologize for passing off the WTWSMS code on the Reddit as yours.
The second thing you need to do is apologize to Loup and hope he is merciful enough to give you one more chance after you committed such an egregious breach of ettiquette and decency as stealing his work.
The third thing you need to do is promise that you will defer to him, like I have to do, in all circumstances.

You are indispensable to this Mod and we NEED you, but Loup has _**very**_ valid reasons why he hates you and wants you nowhere near this Mod.

Start by being the better man: admit your mistakes, apologize to Loup and everyone on the Mod, and grovel.

**Comment by AzimuthEmp** [comment]
I apologise for attempting to steal the mod and pass it off as my own work.
I'm sorry Loup, for stealing your work and then sending you PMs on the forum. I will defer to you in every situation and not question your choices, I promise it.

I have made mistakes and am willing to atone for them, or never talk to you again, whichever you prefer. I can only beg you to do as you see fit.

**Comment by TurtleShroom** [comment]
@AzimuthBlast 

You'd better mean that, Mael, because if you betray Loup and I again, I'll never defend you afterwards.

**Comment by markkduarte** [comment]
Man, I'm a fucking enthusiast of history (degree level etc) and played CK2
since the beginning. The novel that come to my mailbox about three guys
trying to decide the surname of Atilla makes me wanna help.

Em 19/06/2017 17:57, "AzimuthEmp" <notifications@github.com> escreveu:

**Comment by loup99** [comment]
As it would seem like it is a bit unclear, I will clarify once and for all. The mod is developed on the [Paradox Interactive Forums](https://forum.paradoxplaza.com/forum/index.php?forums/) and thus follows and respects the guidelines which exist there. If you do not want to be on those forums for one reason or another, you are free to explain that either on a e-mail or through another channel. I don't want to know an example of a particular personal situation or long justifications here, that belongs to the private domain, not to this repository. No one who isn't on the forums and hasn't discussed it prior will become a developer of the team, in order to avoid repeating past experiences. 

This repository is used to coordinate the modding efforts and share code, it is not, and will never be, a debate platform over moral convictions. You are free to submit issues, as long as they are relevant to the mod, abide by general rules of politeness and are constructive (non-constructive feedback will either get ignored or removed). I promise to read and reply accordingly all issues which abide by those guidelines as time permits it. The replies can be discussed and questioned freely, but if a discussion is locked the discussion is over (unless stated otherwise). 

Posting an issue here does not grant you any copyright or ownership of the mod, and the issues remain suggestions, not material that will always be integrated no matter what. Just because you receive a reply, it doesn't mean that it will be added. If you want to share ideas that you feel particularly attached to and consider to be yours it can be done elsewhere. This mod is only going to be shared by the developers in accordance with the forum rules and that means that the content is credited in case of need, but not owned by those making the suggestions. 

All users who aren't interested in working in this manner can either discuss it privately through the previously mentioned channels (**NOT** here), or create their own project with their preferred standards. This does not mean they have the permission to reuse any of the code in this mod without explicit permission and discussion with the developers and other relevant parties. With that said, I'm closing this issue as it has served its purpose. And, no, I absolutely don't need any oaths or personal swearing of fealty to me, as long as you understand what has been posted here. 

@markkduarte Send me a PM on the forums and I will see what you can help out with.
