### ISSUE TITLE
Byzantine CoA

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#248]
Current byzantine CoA is the tetragrammatic cross, but it became popular **during the Palaiologan period**. I suggest replacing it with Chi Rho [https://en.wikipedia.org/wiki/Chi_Rho](url) or an eagle. More info: [https://en.wikipedia.org/wiki/Byzantine_flags_and_insignia](url)

**Comment by loup99** [comment]
This was what we said on that:
`Also change the flag of the ERE to the Chi Rho flag. They still used that one, probably even to the end of the ERE.`
`I think we must have it, because the current Byzantine flag came into use in the 13th century and the double-headed eagle showed up in the 11th century`
`Agreed.`

**Comment by IhateTrains** [comment]
Do we have Project Augustus author's permission to use his work? WtWSMS team is on his credit list, does it work the other way? If not, I can prepare the CoA myself.

**Comment by loup99** [comment]
We don't. I'm working on the CoA at the moment.

**Comment by loup99** [comment]
Done!

**Comment by IhateTrains** [comment]
This CoA looks cool but it affects unit colors and they look a bit boring. Byzantine units would look much better with on of these variations of your CoA, IMO: https://1drv.ms/f/s!AkkXLHHhb2v-haA9oYa1DeqTxmrr4Q

**Comment by loup99** [comment]
The one I prefer is the golden yellow/red combination. Do you have another preference? Otherwise I will upload that one instead of the white version from the previous commit.

**Comment by IhateTrains** [comment]
I like it too :)
