### ISSUE TITLE
Legions disbanding repeatedly

### ISSUE THREAD

**Issue by IhateTrains** [loup99/WtWSMS#252]
This bug deserves it's own issue because the same events popping up every few days make many interesting (especially early byzantine) starts practically unplayable. I know you can chage culture to latin or byzantine or try the workarounds from the forum, but this is not a solution.

I think the system of legions disbanding depending only on liege's culture is wrong.  Here's my idea:
Legions should never disband in specific Roman realms (e_byzantium, e_wre and succesor states) AND in realms ruled by Latin or Byzantine rulers.

**Comment by loup99** [comment]
> This bug deserves it's own issue because the same events popping up every few days make many interesting (especially early byzantine) starts practically unplayable. I know you can chage culture to latin or byzantine or try the workarounds from the forum, but this is not a solution.

The solution is to solve the bug. As I can't reproduce it due to random crashes, I can't solve it.

> I think the system of legions disbanding depending only on liege's culture is wrong. Here's my idea:
Legions should never disband in specific Roman realms (e_byzantium, e_wre and succesor states) AND in realms ruled by Latin or Byzantine rulers.

The legions disbanding for non-Romance rulers is intended.

**Comment by IhateTrains** [comment]
> The legions disbanding for non-Romance rulers is intended.

I know, but it should be redone. Maybe an option for non-Romance to disband or keep the legions? Did Zeno disband any legions (I don't know)?

**Comment by loup99** [comment]
`I know, but it should be redone. Maybe an option for non-Romance to disband or keep the legions? Did Zeno disband any legions (I don't know)?`
I disagree on redoing this feature. The legions are a powerful force initially, but progressively disbands throughout the centuries. Them being limited to Romance ruler is both for balance concerns and due to it being an unique feature designed for that group. Reconsidering this wouldn't add anything to the mod in my view. Historically it didn't happen over a day of course, but with some features gameplay and coding also has to work.

**Comment by IhateTrains** [comment]
OK then. If you want to reproduce this bug before I finish the secret societies, you can try on later bookmarks. They seem a bit more stable.

**Comment by IhateTrains** [comment]
I have almost finished the societies, yet I'm still experiencing CTDs in years 47X. Maybe societies are not the cause?

**Comment by loup99** [comment]
If the CTDs persist with the secret societies finalised, which would surprise me given that we previously localised them to it, we will have to try other methods for tracking it. Either by manually removing key folders or files to see if it helps, or fixing all log errors and all Validator issues.

**Comment by IhateTrains** [comment]
I would start from log errors, there are only few of them and validator errors are mostly dynasty, character and duplicate problems.

**Comment by loup99** [comment]
I managed to replicate the issue now that I did not get any crash. Will see what can be done.

**Comment by IhateTrains** [comment]
I noticed that vasconic_pagan and vasconic_pagan_reformed don't have religious societies and are not on the list you gave me. Should I add their societies?

**Comment by loup99** [comment]
I have discussed with @tannerflick4 and he is going to finalise the remaining societies.

**Comment by TurtleShroom** [comment]
@IhateTrains  /  @loup99 

I am experiencing a very similar glitch. As the Byzantine Emperor (of Greek culture), my Legions are randomly disbanding as well. After defeating one of my rebellious subjects in a war, I retracted his Legions for my own use. They all suddenly disbanded, _despite the fact that I am of the right culture to hold them_.

The Event was designed to shut down Legions if their liege was not of a Romance or Byzantine culture, and yet, despite that, they still shut down.

That is a bug.****

**Comment by TurtleShroom** [comment]
The worst part is that I'm now under negative two thousand Prestige because so many of them are disbanding.

**Comment by TurtleShroom** [comment]
![untitled](https://user-images.githubusercontent.com/17663470/28038295-683548da-658c-11e7-944e-ea25c17cd6ae.png)

**Comment by IhateTrains** [comment]
It's the biggest bug that's left. We can't release a new version without fixing it.

**Comment by loup99** [comment]
TurtleShroom is talking about something else, which is WAD (although not the repeated events).

**Comment by TurtleShroom** [comment]
The Event was designed to shut down Legions if their liege was not of a Romance or Byzantine culture, and yet, despite that, they still shut down.  

They should be associated to the **_top liege_** and conditional to him being of appropriate Greeco-Roman culture. Otherwise, every time a Viceroyal kingdom is inherited back to the Emperor and is given to a non-Roman, the Legions disband in conditions where it makes absolutely no sense to do so. After all, the Eastern Roman Empire _is still held by a Roman_!

If a Legion is revoked from a vassal and put directly under a Roman character, it's absurd that the Legion would disband. That makes no sense, historically or in the intent of the code. I'd say it's an oversight at best.

Roman Legions should only disband when their top liege is not Rome-compatible. That'll go a long way in fixing the bug that causes reptitive disbanding and respawning of Legionary titles.

**Comment by loup99** [comment]
> The Event was designed to shut down Legions if their liege was not of a Romance or Byzantine culture, and yet, despite that, they still shut down.

I will repeat myself: no, it was not. Here is an explanation of both restoration and the event:

> To restore a legion, you need to enact the "Organize Legion X" decisions, which allows rulers to recreate legions in case **they fully control the required duchy or kingdom** _and_ **are of the Romance culture group**.

As you see, it takes two to tango.

> That'll go a long way in fixing the bug that causes reptitive disbanding and respawning of Legionary titles.

It won't at all, because the bug is that disbanding legions does not work.

**Comment by TurtleShroom** [comment]
The problem is that the ERE does fully control that duchy or kingdom. Legions disbanding while the ERE is still of the Romance culture group makes no sense. The point of the code was that the ERE (or WRE, etc.) top liege needed to fully control the duchy or kingdom AND be of the Romance culture group, otherwise the Legions would disband.

Simply put, I believe that the _top liege_ should completely control the duchy or kingdom and be of a Romance culture in order for Legions to be disbanded.

In actuality, I'd prefer there to be a rule governing Legions disbanding that address this.

**Comment by TurtleShroom** [comment]
In actuality, I'd prefer there to be a Rule governing Legions disbanding that addresses this. One keeps the setup as-is, one requires the top liege to be Romance and fully control it, and one allows Legions to always exist.

**Comment by loup99** [comment]
This is a separate matter. I'm going to move these posts.

**Comment by IhateTrains** [comment]
The issue should now be solved :D
