### ISSUE TITLE
Secret Religions - Missing Indicator

### ISSUE THREAD

**Issue by OdinMyst** [loup99/WtWSMS#339]
Hello again!

I hope I'm not being too much of a bother, but I think I found another small issue. 
I've done a few New Game tests, and whenever I adopt a secret religion and create the respective sect, and then invite other people and they accept, that little round indicator next to their openly adopted faith never shows up. On the character finder none but me appear either.
On the other hand, the ones who enter the secret cult show up on the member list (even though they still appear without the secret religion indicator on their profile), and in the save game file the "secret_religion" modifier is present.

If anyone knows any sort of fix, specially if save game compatible, like direct save file editing or something, drop me a line.

Thank you. Best regards.

**Comment by loup99** [comment]
Hi,
no problems, keep reporting as much as you find!

This graphical issue you describe is strange, because I did a quick test and couldn't reproduce it with Miaphysite/Nicene. Maybe it occurs for some particular secret religions? Which one have you tested?

Here is how it looked for my character:
![ck2_29](https://user-images.githubusercontent.com/7620180/32140943-af301868-bc72-11e7-9b68-5340eca53292.png)

**Comment by xirsoi** [comment]
The problem is probably here: https://github.com/loup99/WtWSMS/blob/master/WTWSMS/common/religions/00_religions.txt#L5

Should be an OR.

**Comment by loup99** [comment]
That is indeed the error which causes this! Thank you for pointing it out @xirsoi !

**Comment by OdinMyst** [comment]
Sorry about the late reply. Yeah I just tested it, and the bug is indeed fixed. Great job guys!

**Comment by xirsoi** [comment]
I'm also the one who made the bug :(

It was fixed in the next version of ARR but updating the ARR in WtWSMS takes time.
